//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppInstaller.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppInstaller.Resources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string Btn_Cancel {
            get {
                return ResourceManager.GetString("Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一步 &gt; 的本地化字符串。
        /// </summary>
        internal static string Btn_Next {
            get {
                return ResourceManager.GetString("Btn_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt; 上一步 的本地化字符串。
        /// </summary>
        internal static string Btn_Pre {
            get {
                return ResourceManager.GetString("Btn_Pre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这个向导将引导您完成%s的安装。在开始安装之前，请确保%s没有正在运行。点击“下一步”继续。 的本地化字符串。
        /// </summary>
        internal static string Default_Welcome_Content_Statement {
            get {
                return ResourceManager.GetString("Default_Welcome_Content_Statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎使用%s安装程序. 的本地化字符串。
        /// </summary>
        internal static string Default_Welcome_Statement {
            get {
                return ResourceManager.GetString("Default_Welcome_Statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装 的本地化字符串。
        /// </summary>
        internal static string Group_Installer_Name {
            get {
                return ResourceManager.GetString("Group_Installer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 许可协议 的本地化字符串。
        /// </summary>
        internal static string Label_License_Agreement {
            get {
                return ResourceManager.GetString("Label_License_Agreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请在安装%s之前查看许可证条款 的本地化字符串。
        /// </summary>
        internal static string Label_License_Agreement_Tip {
            get {
                return ResourceManager.GetString("Label_License_Agreement_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 遵循 {1}许可证进行分发。 的本地化字符串。
        /// </summary>
        internal static string License_Tip {
            get {
                return ResourceManager.GetString("License_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同意 的本地化字符串。
        /// </summary>
        internal static string RadioBtn_Agree {
            get {
                return ResourceManager.GetString("RadioBtn_Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不同意 的本地化字符串。
        /// </summary>
        internal static string RadioBtn_Disagree {
            get {
                return ResourceManager.GetString("RadioBtn_Disagree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 %s 安装向导 的本地化字符串。
        /// </summary>
        internal static string Title_Setup {
            get {
                return ResourceManager.GetString("Title_Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎 的本地化字符串。
        /// </summary>
        internal static string Title_Welcome {
            get {
                return ResourceManager.GetString("Title_Welcome", resourceCulture);
            }
        }
    }
}
